compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: '/work/zhangyaqing/ChatGLM2-6B/accelerate_deepspeed/ds_config.json'
distributed_type: DEEPSPEED
num_machines: 1
machine_rank: 0
num_processes: 1
use_cpu: false
fsdp_config: {}
same_network: true
downcast_bf16: 'no'
dynamo_backend: 'NO'
main_process_port: 29400
rdzv_backend: static
megatron_lm_config: {}
main_training_function: main


