compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: '/work/zhangyaqing/accelerate_deepspeed/llm/config/ds_config.json'
distributed_type: DEEPSPEED
num_machines: 1
machine_rank: 0
num_processes: 3
use_cpu: false
fsdp_config: {}
same_network: true
downcast_bf16: 'no'
dynamo_backend: 'NO'
rdzv_backend: static
megatron_lm_config: {}
main_training_function: main


