prompt: 'a professional photograph of an astronaut riding a triceratops'
outdir: 'outputs/txt2img-samples'
steps: 50
plms: true
dpm: true
fixed_code: true
ddim_eta: 0.0
n_iter: 3
H: 512
W: 512
C: 4
f: 8
n_samples: 3
n_rows: 0
scale: 9.0
from-file: ''
config: 'configs/stable-diffusion/v2-inference.yaml'
ckpt: ''
seed: 42
precision: 'autocast'  # [full, autocast]
repeat: 1
device: 'cuda'  # [cpu, cuda]
torchscript: true
ipex: true
bf16: true